language: node_js
node_js:
  - v8
script:
  - npm run coverage
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a124e3287dc714e8d05a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always